require('dotenv/config');
const express = require('express');
const bodyParser = require('body-parser');
const app = express();
var cors = require('cors');
app.use(cors());
const port = process.env.PORT || 4000;
const productRouter = require('./src/routes/products.routes.js');
const paymentRouter = require('./src/routes/payments.routers.js');
app.use(bodyParser.json());
app.use('/api/v1/product', productRouter);
app.use('/api/v1/payment', paymentRouter);
app.listen(port, () => { console.log(`Server is listening on port ${port}`); });